# global settings
output_dir: data/
crs: EPSG:32604
output_name: "hi_nhf_v1.0.0.gpkg" # If not specified, will default to version

# hf builds
build:
  reference_divides_path: data/reference/hi_0.1.3_reference_divides.parquet
  reference_flowpaths_path: data/reference/hi_0.1.3_reference_flowpaths.parquet
  # debug_outlet_count: 2000 # If specified, only the total amount of rivers here will be built
  divide_aggregation_threshold: 3.0

# choose tasks to run
tasks:
  build_hydrofabric: True
  divide_attributes: False
  flowpath_attributes: False
  waterbodies: False
  hydrolocations: False
  gages: False
  fp_crosswalk: False
